# Generated by Django 5.0.4 on 2024-05-20 16:43

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseoutline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outline',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outline',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('lecturer', 'Giảng viên'), ('student', 'Sinh viên')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='approval',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseoutline.student', unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
